version: '2.4'
# es la version del docker compose

services:
  data-exploration:
    image: tensorflow/tensorflow:1.14.0-py3-jupyter
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - /Users/hdla/data:/data
      - ./mile:/code
      - ./notebooks:/notebooks
    working_dir: /notebooks
    command: jupyter notebook --no-browser --allow-root --ip 0.0.0.0 --NotebookApp.custom_display_url=http://localhost:8888
    # command: bash
    # stdin_open: true
    # tty: true #Terminal explorer