# name: vision
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#     - pip
#     - python=3.8
#     - pip>=19.0
#     - pandas
#     - matplotlib
#     - pillow
#     - pylint
#     - ipython
#     - ipykernel
#     - autopep8
#     - opencv
#     - imutils
#     - camelot-py
#     - pdf2image
#     - pytesseract
#     - jinja2

# conda install -c conda-forge opencv   --- ok win and linux

# opencv-contrib-python==3.4.4.19
# pillow>=6.2.0
# pytesseract==0.2.6

# Se requiere instalar posteriormente este
# conda install -c conda-forge imutils

# conda install -c conda-forge camelot-py
# pip install camelot-py[cv]

# conda install -c conda-forge pdf2image

# sudo apt-get install tesseract-ocr --- ok funcionó
# conda install -c conda-forge pytesseract
# sudo apt-get install tesseract-ocr-spa -y
#### tesseract --list-langs

# conda install -c anaconda jinja2

# pip install tensorflow
# pip install --upgrade tensorflow-hub


#conda env create -f environment.yml
#conda env update --prefix ./env --file requirements.yml --prune

# git rm --cached .vscode/settings.json
# %time, %timeit and %%time